# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: jsoutelo <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2017/11/09 16:13:33 by jsoutelo          #+#    #+#              #
#    Updated: 2017/11/11 18:55:43 by jsoutelo         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = ft_display_file

FILE = $(NAME).c

all: $(NAME)

$(NAME):
	gcc -Wall -Werror -Wextra -o $(NAME) $(FILE)

clean:
	/bin/rm -f *.o 

fclean: clean
	/bin/rm -f $(NAME)
